#!/bin/sh

pkg update
pkg upgrade -y
pkg install -y \
    git \
    build-essential \
    emacs \
    openssh \
    termux-api \
    python \
    python-numpy \
    python-scipy \
    matplotlib

pip install \
    lcapy==1.24
