#!/bin/sh
set -e

pkg update
pkg upgrade -y
pkg install -y \
    build-essential \
    emacs \
    git \
    lazygit \
    man \
    openssh \
    termux-api \
    zsh \
    python \
    python-numpy \
    python-scipy \
    matplotlib

pip install \
    lcapy==1.24
